"""Initial migration

Revision ID: ebcc7136f32b
Revises: 
Create Date: 2024-08-22 09:57:46.925885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebcc7136f32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order of their creation to avoid foreign key constraint issues
    op.drop_table('conta_a_pagar')
    op.drop_table('credor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate tables in the correct order
    op.create_table('credor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conta_a_pagar',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('valor', mysql.FLOAT(), nullable=False),
    sa.Column('data_vencimento', sa.DATE(), nullable=False),
    sa.Column('status_conta', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('credor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credor_id'], ['credor.id'], name='conta_a_pagar_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
