"""Adiciona campo data_pagamento a ContaAPagar

Revision ID: e1bb4b54950f
Revises: 
Create Date: 2024-08-31 21:38:17.055051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1bb4b54950f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta_a_pagar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pagamento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('multa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('juros', sa.Float(), nullable=True))
        batch_op.alter_column('descricao',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('valor',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('data_vencimento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('status_conta',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('credor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('credor', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('cnpj',
               existing_type=mysql.VARCHAR(length=18),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('endereco',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credor', schema=None) as batch_op:
        batch_op.alter_column('endereco',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=mysql.VARCHAR(length=18),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('conta_a_pagar', schema=None) as batch_op:
        batch_op.alter_column('credor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('status_conta',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('data_vencimento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('valor',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('juros')
        batch_op.drop_column('multa')
        batch_op.drop_column('data_pagamento')

    # ### end Alembic commands ###
